services:

  example-frontend:
    image: example-frontend:latest
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    command: ["serve", "-s", "-l", "5000", "build"]

  example-backend:
    image: example-backend:latest
    build: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    depends_on:
      - db
    entrypoint: ["./server"]

  redis:
    image: redis:latest
    command: ["redis-server", "--save 60 1", "--loglevel warning"]

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db-example
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data

